resources:
  - ../../base

namespace: weather-checker

images:
  - name: hemraj43/weather-checker
    newName: hemraj43/weather-checker
    newTag: 0.0.1   #can be captured from pipeline

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: weather-checker
    path: patch-deployment.yaml
  - target:
      kind: Service
      name: weather-checker
    path: patch-svc.yaml

configMapGenerator:
  - name: weather-checker-config
    behavior: merge
    envs:
      - patch-config.env