- op: replace
  path: "/spec/template/spec/containers/0/imagePullPolicy"
  value: "Always"
- op: replace
  path: "/spec/template/spec/containers/0/resources/limits/cpu"
  value: "500m"
- op: replace
  path: "/spec/template/spec/containers/0/resources/limits/memory"
  value: "500Mi"