apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-checker
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels: &labels
      app: weather-checker
      tier: frontend
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: weather-checker
          image: hemraj43/weather-checker:0.0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: weather-checker-config
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "300m"


---
