apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - svc.yaml

commonAnnotations:
  infraview.net/maintainer: Hem Raj

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: weather-checker-config
    behavior: create
    envs:
      - config.env
