apiVersion: v1
kind: Service
metadata:
  name: weather-checker
  labels: &labels
    app: weather-checker
    tier: frontend
spec:
  selector:
    <<: *labels
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
---